### PR TITLE
6 - development strategy plan PR

### PR DESCRIPTION
**Pull request by Melati5**
## General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

### HTML

- [ ] pages besides `/index.html` are stored in `/pages`
- [ ] the code is well-formatted
- [ ] the HTML is valid
- [ ] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [ ] semantic tags are used
- [ ] spelling and grammar is correct in all site content

### CSS

- [ ] the code is well-formatted
- [ ] passes all the linting checks

### CODE REVIEW

**Review by Dnyandeo33 — CHANGES_REQUESTED** [review]
Development strategy should be created as per requirement given in backlog. for example how our website should look. how we can develop it. but you wrote about project development strategy. hence we need to write about website development strategy.

**Comment by Melati5** [comment]
> Development strategy should be created as per requirement given in backlog. for example how our website should look. how we can develop it. but you wrote about project development strategy. hence we need to write about website development strategy.

Yes l am aware that development strategy should be writen according to the "must have user stories" in the backlog and currently our development strategy.md file includes our website development strategy according to the user stories in the backlog. l also mentioned about that in our meeting today.
But I also added our group conventions to the development strategy as @TheRick88  has requested in our discord group discussions in the task sharing: https://discord.com/channels/894607053367181402/953659689562943569/955865556135845918

**Comment by Melati5** [comment]
> > Development strategy should be created as per requirement given in backlog. for example how our website should look. how we can develop it. but you wrote about project development strategy. hence we need to write about website development strategy.
> 
> Yes l am aware that development strategy should be writen according to the "must have user stories" in the backlog and currently our development strategy.md file includes our website development strategy according to the user stories in the backlog. l also mentioned about that in our meeting today. But I also added our group conventions to the development strategy as @TheRick88 has requested in our discord group discussions in the task sharing: https://discord.com/channels/894607053367181402/953659689562943569/955865556135845918

As backlog is updated, l'll also update the development strategy file according to the must have user stories added in the backlog

**Comment by TheRick88** [comment]
@Melati5  Ive sent you on discord the info you can add here, I can explain it to you step by step tomorrow.

**Comment by Melati5** [comment]
Should there any changes be made to this file?
If not , could you please merge it to the master?  @TheRick88 @Dnyandeo33 @inna9Z

**Comment by TheRick88** [comment]
> Should there any changes be made to this file? If not , could you please merge it to the master? @TheRick88 @Dnyandeo33 @inna9Z

Hello! Yeah, can you add what I sent you to the chat about the sections of the website and the tech we will use for each? (html and css)

**Pull request closed without merging**
